### ISSUE TITLE
The use of `io::Result` instead of `futures::Async`

### ISSUE THREAD

**Issue by rotty** [tokio-rs/tokio-uds#4]
I noticed that, contrary to my unsubstantiated expectations, that`UnixDatagram::{send, recv}` return `io::Result`, instead of turning`WouldBlock` errors into `futures::Async::NotReady`.

It's not clear to me what result types are approriate for each layer -- I'd have assumed `io::Result` in mio, and public, but primitive methods (like `send` and `recv`) in tokio-based APIs would use some `Async` type variant.

I'm asking not due to API usability issues, but since I am trying using `tokio-uds` as a blueprint for [`zmq-tokio`](https://github.com/rotty/zmq-tokio).

This is really one of the biggest hurdles for me: that there's no blueprint I'm totally confident in having the API types right, and no docs explaining how it *should* be done, and *why*.

If I reach sufficient understanding, I can maybe come up with a documentation patch for tokio-core that explains the design ideas behind that, but right now I'm at quite a loss.

**Comment by alexcrichton** [comment]
Thanks for the report! Right now this crate mirrors the APIs of UDP/TCP in tokio-core itself, so this is really more of an upstream issue there rather than for this repository itself.

For now, though, the rule of thumb is:

* `poll` methods (e.g. with `poll` in the name) always return something with `Async`
* I/O methods match their underlying counterparts, but are nonblocking. E.g. they return "would block" errors

We may consider unifying these two strategies under one umbrella eventually, but for now we're at where we're at :(

**Comment by rotty** [comment]
Thanks for the explanation; it's not that I find it hard to understand, but I was irritated by the existence of two essentially equivalent ways of expressing the same thing, and was wondering whether I was missing some important underlying reason for this difference.

I'm closing this now, as the issue (if any) is with `tokio-core` documentation.
